// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ordndjsitozrqewligwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZG5kanNpdG96cnFld2xpZ3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTE2MTUsImV4cCI6MjA2NzI2NzYxNX0.cGox0Ju7ZDdookCHQAQGv57CWgdnM8kjVeGAtLvu93E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});